import { Link, useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import { object, string } from "yup";
import { getErrorMessage } from "../../api/response";
import { AuthLayout } from "../../components/auth/AuthLayout";
import { Button, PasswordInput, Text, TextInput } from "../../components/ui";
import { toastError, toastSuccess } from "../../lib/toast";
import authService, { type SignupRequest } from "../../services/auth.service";
const schema = object({ name: string().trim().min(2, "Name must be at least 2 characters").max(80).required("Name is required"), contactNumber: string().trim().matches(/^\d{10}$/, "Enter a valid 10-digit contact number").required("Contact number is required"), password: string().min(8, "Password must be at least 8 characters").matches(/[A-Za-z]/, "Include at least one letter").matches(/\d/, "Include at least one number").required("Password is required") });
export default function Signup() { const navigate = useNavigate(); const { register, handleSubmit, formState: { errors, isSubmitting }, setError } = useForm<SignupRequest>({ resolver: yupResolver(schema), defaultValues: { name: "", contactNumber: "", password: "" } }); const onSubmit = handleSubmit(async values => { try { const response = await authService.signup({ ...values, name: values.name.trim(), contactNumber: values.contactNumber.trim() }); toastSuccess(response.message); navigate("/login", { replace: true }); } catch (error) { const message = getErrorMessage(error, "Account creation failed. Please try again."); setError("root", { message }); toastError(message); } });
  return <AuthLayout title="Create your account" subtitle="Get started with your coaching workspace.">{errors.root?.message && <div className="mb-5 rounded-md border border-danger/30 bg-danger/10 p-3 text-sm text-danger" role="alert">{errors.root.message}</div>}<form onSubmit={onSubmit} noValidate className="space-y-5"><TextInput label="Full name" autoComplete="name" placeholder="Mohit" required error={errors.name?.message} {...register("name")}/><TextInput label="Contact number" inputMode="numeric" autoComplete="tel" placeholder="1234567894" required error={errors.contactNumber?.message} {...register("contactNumber")}/><PasswordInput label="Password" autoComplete="new-password" placeholder="At least 8 characters" required helperText="Use at least 8 characters with a letter and number." error={errors.password?.message} {...register("password")}/><Button type="submit" loading={isSubmitting} fullWidth>Create account</Button></form><Text variant="muted" className="mt-7 text-center">Already have an account? <Link className="font-semibold text-primary hover:underline" to="/login">Sign in</Link></Text></AuthLayout>; }
