import * as DialogPrimitive from "@radix-ui/react-dialog";
import { X } from "lucide-react";
import type { ReactNode } from "react";
import { cn } from "../../lib/cn";
import { Button } from "./Button";
import { SubHeading, Text } from "./typography";

interface ModalProps { open: boolean; onOpenChange: (open: boolean) => void; title: string; description?: string; children?: ReactNode; footer?: ReactNode; size?: "sm" | "md" | "lg"; }
const sizeClasses = { sm: "max-w-sm", md: "max-w-lg", lg: "max-w-3xl" };
export function Modal({ open, onOpenChange, title, description, children, footer, size = "md" }: ModalProps) { return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out"/><DialogPrimitive.Content className={cn("fixed left-1/2 top-1/2 z-[60] max-h-[85vh] w-[calc(100%-2rem)] -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-lg border bg-surface shadow-lg", sizeClasses[size])}><div className="border-b p-6 pr-14"><DialogPrimitive.Title asChild><SubHeading>{title}</SubHeading></DialogPrimitive.Title>{description && <DialogPrimitive.Description asChild><Text variant="muted" className="mt-1">{description}</Text></DialogPrimitive.Description>}</div><DialogPrimitive.Close asChild><Button variant="ghost" size="icon" className="absolute right-4 top-4" aria-label="Close dialog"><X className="size-4"/></Button></DialogPrimitive.Close>{children && <div className="p-6">{children}</div>}{footer && <div className="flex justify-end gap-3 border-t p-4">{footer}</div>}</DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>; }
export function Drawer({ open, onOpenChange, title, description, children, footer }: Omit<ModalProps, "size">) { return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/60"/><DialogPrimitive.Content className="fixed inset-y-0 right-0 z-[60] flex w-[min(28rem,90vw)] flex-col border-l bg-surface shadow-lg"><div className="border-b p-6 pr-14"><DialogPrimitive.Title asChild><SubHeading>{title}</SubHeading></DialogPrimitive.Title>{description && <DialogPrimitive.Description asChild><Text variant="muted">{description}</Text></DialogPrimitive.Description>}</div><DialogPrimitive.Close asChild><Button variant="ghost" size="icon" className="absolute right-4 top-4" aria-label="Close drawer"><X className="size-4"/></Button></DialogPrimitive.Close><div className="flex-1 overflow-y-auto p-6">{children}</div>{footer && <div className="flex justify-end gap-3 border-t p-4">{footer}</div>}</DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>; }
interface ConfirmationProps { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; confirmLabel?: string; cancelLabel?: string; loading?: boolean; onConfirm: () => void; danger?: boolean; }
export function ConfirmationDialog({ open, onOpenChange, title, description, confirmLabel = "Confirm", cancelLabel = "Cancel", loading, onConfirm, danger }: ConfirmationProps) { return <Modal open={open} onOpenChange={onOpenChange} title={title} description={description} size="sm" footer={<><Button variant="outline" onClick={() => onOpenChange(false)}>{cancelLabel}</Button><Button variant={danger ? "danger" : "primary"} loading={loading} onClick={onConfirm}>{confirmLabel}</Button></>}/>; }
export function DeleteDialog(props: Omit<ConfirmationProps, "danger" | "confirmLabel"> & { confirmLabel?: string }) { return <ConfirmationDialog {...props} danger confirmLabel={props.confirmLabel ?? "Delete"}/>; }
